### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by Dimon20012008** [platondr/CV_Theremin#3]
1. Lower boundaries for volume are too low: sometimes programm does not detect finger, when it is next to the bar.
2. If you twitch your hand fast, programm will sometimes detect one hand as two. Not critical, but exists and can be annoying while recording
Suggestion: it is not obivious, that change of volume and pitch accures when you move towards the line, not along it. Probably some arrows will help.

**Comment by platondr** [comment]
1. It does, the volume is just too low for the sound to be heard and it seems that it is absent
2. This is just how a theremin works, the instruction on how to use it were specified in the README file
