### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Sundew999666** [platondr/CV_Theremin#4]
1. Нужно добавить критерии использования приложения к примеру программа работает даже при том случае, когда оба пальца находятся в одной половине поля
2. Добавить текст о том, что требуется скачать файл "audio_generation" в README

**Comment by platondr** [comment]
1. Программа пишет красным текстом, что в кадре должны быть обе руки, но в README добавлю
2. Очевидно, что скачивая программу надо скачать все ее программные файлы, но в README на всякий случай добавил
